/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "quitoque.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
quitoque_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		client ajout_client_1_arg;
		int afficher_client_1_arg;
		client modifier_client_1_arg;
		type_chaine rechercher_recette_1_arg;
		panier ajout_au_panier_1_arg;
		int afficher_panier_1_arg;
		panier supprimer_recette_au_panier_1_arg;
		commande effectuer_commande_1_arg;
		int afficher_commande_1_arg;
		livraison programmer_livraison_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) init_1_svc;
		break;

	case ajout_client:
		_xdr_argument = (xdrproc_t) xdr_client;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) ajout_client_1_svc;
		break;

	case afficher_client:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_client;
		local = (char *(*)(char *, struct svc_req *)) afficher_client_1_svc;
		break;

	case modifier_client:
		_xdr_argument = (xdrproc_t) xdr_client;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) modifier_client_1_svc;
		break;

	case rechercher_recette:
		_xdr_argument = (xdrproc_t) xdr_type_chaine;
		_xdr_result = (xdrproc_t) xdr_recettes;
		local = (char *(*)(char *, struct svc_req *)) rechercher_recette_1_svc;
		break;

	case ajout_au_panier:
		_xdr_argument = (xdrproc_t) xdr_panier;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) ajout_au_panier_1_svc;
		break;

	case afficher_panier:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_panier;
		local = (char *(*)(char *, struct svc_req *)) afficher_panier_1_svc;
		break;

	case supprimer_recette_au_panier:
		_xdr_argument = (xdrproc_t) xdr_panier;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) supprimer_recette_au_panier_1_svc;
		break;

	case effectuer_commande:
		_xdr_argument = (xdrproc_t) xdr_commande;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) effectuer_commande_1_svc;
		break;

	case afficher_commande:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_commande;
		local = (char *(*)(char *, struct svc_req *)) afficher_commande_1_svc;
		break;

	case programmer_livraison:
		_xdr_argument = (xdrproc_t) xdr_livraison;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) programmer_livraison_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (QUITOQUE_PROG, QUITOQUE_1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, QUITOQUE_PROG, QUITOQUE_1, quitoque_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (QUITOQUE_PROG, QUITOQUE_1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, QUITOQUE_PROG, QUITOQUE_1, quitoque_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (QUITOQUE_PROG, QUITOQUE_1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
