/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quitoque.h"


void
quitoque_prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	int  *result_2;
	client  ajout_client_1_arg;
	client  *result_3;
	int  afficher_client_1_arg;
	int  *result_4;
	client  modifier_client_1_arg;
	recettes  *result_5;
	type_chaine  rechercher_recette_1_arg;
	int  *result_6;
	panier  ajout_au_panier_1_arg;
	panier  *result_7;
	int  afficher_panier_1_arg;
	int  *result_8;
	panier  supprimer_recette_au_panier_1_arg;
	int  *result_9;
	commande  effectuer_commande_1_arg;
	commande  *result_10;
	int  afficher_commande_1_arg;
	int  *result_11;
	livraison  programmer_livraison_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, QUITOQUE_PROG, QUITOQUE_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	strcpy(ajout_client_1_arg.nom,"EL AATFI");
    	strcpy(ajout_client_1_arg.prenom,"MOHAMED");
    	strcpy(ajout_client_1_arg.adresse,"Rue Jules");
    	ajout_client_1_arg.tele=4563;
    	ajout_client_1_arg.carteBancaire=0;
    	
    	
	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = ajout_client_1(&ajout_client_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	            printf("-->> Inscription reussi le client est ajoute <<-- \n\n");
	}
	afficher_client_1_arg=0;
	result_3 = afficher_client_1(&afficher_client_1_arg, clnt);
	if (result_3 == (client *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("-->> AFFICHAGE DES INFORMATIONS DU CLIENT  <<--\n");
    printf("\tNOM :  %s\n", result_3->nom);
    printf("\tPRENOM:  %s\n", result_3->prenom);
    printf("\tTELE:  %d\n", result_3->tele);
    printf("\tCarte  :   %ld\n", result_3->carteBancaire);
    //-------------------------------------------------
   }  int a,b=0,d,tel,c;
    char nom[20]="momo";
    char prenom[20];
    
    printf("-->> MODIFIER LE CONTENUE DU CARTE BANCAIRE DU CLIENT <<-- \n");
  
    //modification les informations du client 
    
    		
	modifier_client_1_arg.id=b;
	strcpy(modifier_client_1_arg.nom,nom);
    	strcpy(modifier_client_1_arg.prenom,"MOHAMED");
    	strcpy(modifier_client_1_arg.adresse,"Rue Jules");
    	modifier_client_1_arg.tele=4563;
    	modifier_client_1_arg.carteBancaire=4564;

	result_4 = modifier_client_1(&modifier_client_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("--LA MODIFICATION EST BIEN EFFECTUER--\n");
		result_3 = afficher_client_1(&afficher_client_1_arg, clnt);
		if (result_3 == (client *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
	    printf("-->> AFFICHAGE LES INFORMATIONS APRES LA MODIFICATION DANS LA BASE DU CLIENT  <<-- \n");
	    printf("\tNOM :  %s\n", result_3->nom);
	    printf("\tPRENOM:  %s\n", result_3->prenom);
	    printf("\tTELE:  %d\n", result_3->tele);
	    printf("\tCarte  :   %ld\n", result_3->carteBancaire);
	    }
	}
	//-------------------------------------------------------

	strcpy(rechercher_recette_1_arg.chaine,"Vegetarie");
	result_5 = rechercher_recette_1(&rechercher_recette_1_arg, clnt);
	if (result_5 == (recettes *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("-->> AFFICHER LES RECETTES SELON UN CRITERE <<-- \n");
	printf("-->> FILTRER PAR TYPE --VEGETARIEN-- <<-- \n");
	int i;
	for (i = 0; i < result_5->nbRecette; i++) {
		printf("Recettes : %d\n",i+1);
		printf("\tid : %d\n", result_5->listeRecette[i].id);
		printf("\tnom : %s\n", result_5->listeRecette[i].nom);
		printf("\tTYPE : %s\n", result_5->listeRecette[i].type);
		printf("\tPRIX : %f EURO\n", result_5->listeRecette[i].prix);
	}
	
	}
	ajout_au_panier_1_arg.id=0;
	ajout_au_panier_1_arg.idC=1;
	ajout_au_panier_1_arg.id_recette[0]=1;
	ajout_au_panier_1_arg.id_recette[1]=2;
	ajout_au_panier_1_arg.id_recette[2]=3;

	ajout_au_panier_1_arg.total=0.0;
	result_6 = ajout_au_panier_1(&ajout_au_panier_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("-->>AJOUTER LES RECETTE AU PANIER <<--\n");
	printf("-->>ajouter les recettes d'id 1 et 2 et 3 <<--\n");
	}
	afficher_panier_1_arg=0;
	result_7 = afficher_panier_1(&afficher_panier_1_arg, clnt);
	if (result_7 == (panier *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("-->>AFFICHAGE DU PANIER <<--\n");
		int i;
		printf("Panier : %d\n",1);
		printf("\tid Client : %d\n", result_7->idC);
		for (i = 0; i < 3; i++) {
			printf("\tid Recette: %d\n", result_7->id_recette[i]);
		}
		printf("\tPRIXTotal : %f EURO\n", result_7->total);
	
	}
	//--------------------------------------------------
	
	supprimer_recette_au_panier_1_arg.id=0;
	supprimer_recette_au_panier_1_arg.idC=1;
	supprimer_recette_au_panier_1_arg.id_recette[0]=1;
	supprimer_recette_au_panier_1_arg.id_recette[1]=2;
	supprimer_recette_au_panier_1_arg.id_recette[2]=0;
	supprimer_recette_au_panier_1_arg.total=0.0;
	result_8 = supprimer_recette_au_panier_1(&supprimer_recette_au_panier_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("-->> RETIRE UNE RECETTE DE PANIER <<--\n");
		printf("la suppression du recette est bien effectuer\n");
		

		result_7 = afficher_panier_1(&afficher_panier_1_arg, clnt);
		if (result_7 == (panier *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
		printf("-->> AFFICHAGE DU PANIER APRES LA MODIFICATION <<--\n");
			int i;
			printf("Panier : %d\n",1);
			printf("\tid Client : %d\n", result_7->idC);
			for (i = 0; i < 10; i++) {
				if(result_7->id_recette[i] != 0){
					printf("\tid Recette: %d\n", result_7->id_recette[i]);
				}
			}
			printf("\tPRIXTotal : %f EURO\n", result_7->total);
		
		}
		
	}
	effectuer_commande_1_arg.idPanier = 1;
	effectuer_commande_1_arg.date.day=18;
	effectuer_commande_1_arg.date.mounth=03;
	effectuer_commande_1_arg.date.year=2022;
	effectuer_commande_1_arg.qte=11;

	strcpy(effectuer_commande_1_arg.etat,"O");
	result_9 = effectuer_commande_1(&effectuer_commande_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("-->> VALIDER LA COMMANDE <<--\n");
	}	
	afficher_commande_1_arg=1;
	result_10 = afficher_commande_1(&afficher_commande_1_arg, clnt);
	if (result_10 == (commande *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	    printf("-->> LES INFORMATION DU COMMANDE <<-- \n");
	    printf("\tLa date du livraison %d/%d/%d\n", result_10->date.day,result_10->date.mounth,result_10->date.year);
	    printf("\tQuantite:  %d\n", 2);
	    printf("\tAdress du livraison:  %s\n",result_3->adresse );
	}
	programmer_livraison_1_arg.idCommande=1;
	programmer_livraison_1_arg.date.day=12;
	programmer_livraison_1_arg.date.mounth=3;
	programmer_livraison_1_arg.date.year=2012;
	strcpy(programmer_livraison_1_arg.type,"Rapide");
	strcpy(programmer_livraison_1_arg.adresse,"RueJyles Lesv");
	
	
	
	result_11 = programmer_livraison_1(&programmer_livraison_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	
	printf("-->> LA LIVRAISON EST PROGRAMME <<-- \n");
	printf("-->> Votre Commande est en route Merci pour votre confiance<<-- \n");
	
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	quitoque_prog_1 (host);
exit (0);
}
