/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quitoque.h"

int nbClient;
client listClient[10];

commande listCommande[5];
int nbCommande=0;

recette listRecette[10];
int nbRecette;

int ajoutClient=0;

panier listPanier[10];
int indicePanier=0;

livraison listLivraison[10];
int nbLivraison=0;

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*initialiser client*/
int i;
	for(i=0;i<10;i++){
		listClient[i].id=i;
		strcpy(listClient[i].nom,"EL AATFI");
		strcpy(listClient[i].prenom,"Med");
		strcpy(listClient[i].adresse,"RueJulesLesven");
		listClient[i].tele=466;
		listClient[i].carteBancaire=7675;
		nbClient++;
	}
	
 
	 
	 //initialise recette
	 for (i = 0; i < 10; i++) {
		listRecette[i].id = i+1;
		if(i%2==0){
		
		strcpy(listRecette[i].type,"Vegetarie");
		strcpy(listRecette[i].ingrediant,"Fromage-Miel-PatateDouce-Poulet");
		listRecette[i].nbPart=2;
		listRecette[i].prix=9+(i+10);
		strcpy(listRecette[i].disponible,"O");
		}else{
		
		strcpy(listRecette[i].type,"Viande");
		strcpy(listRecette[i].ingrediant,"Tomate-Mozarella-huile-ognion");
		listRecette[i].nbPart=3;
		listRecette[i].prix=10+(i+10);
		strcpy(listRecette[i].disponible,"O");
		}
		
        nbRecette++;
	}
	strcpy(listRecette[0].nom,"Tenders");
	strcpy(listRecette[1].nom,"Poulet");
	strcpy(listRecette[2].nom,"Tacos");
	strcpy(listRecette[3].nom,"Salade");
	strcpy(listRecette[4].nom,"Burger");
	strcpy(listRecette[5].nom,"Pizza");
	strcpy(listRecette[6].nom,"Tajin");
	strcpy(listRecette[8].nom,"soupe");
	strcpy(listRecette[9].nom,"suchi");

	//initialiser Panier
int k,j=1;
	for(i=0;i<10;i++){
	
		listPanier[i].id=j;
		listPanier[i].idC=0;
		for(k=0;k<10;k++)
			listPanier[i].id_recette[k]=0;
		j++;
	}



	return (void *) &result;
}

int *
ajout_client_1_svc(client *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("-------------------------------------------------\n");
	strcpy(listClient[ajoutClient].nom,argp->nom);
	strcpy(listClient[ajoutClient].prenom,argp->prenom);
	strcpy(listClient[ajoutClient].adresse,argp->adresse);
	listClient[ajoutClient].tele=argp->tele;
	listClient[ajoutClient].carteBancaire=argp->carteBancaire;
	ajoutClient++;
	printf("--l'ajout du client est bien--\n");
	printf("-------------------------------------------------\n");
	result = 1;
	return &result;
}

client *
afficher_client_1_svc(int *argp, struct svc_req *rqstp)
{
static client  result;

	int i;
	for(i=0;i<nbClient; i++){ 
        	if (listClient[i].id==*argp){
		    strcpy(result.nom,listClient[i].nom);
		    strcpy(result.prenom,listClient[i].prenom);
		    result.tele=listClient[i].tele;
		    strcpy(result.adresse,listClient[i].adresse);
		    result.carteBancaire=listClient[i].carteBancaire;
		    printf("--l'affichage du client est bien--\n");
		    printf("-------------------------------------------------\n");
        }
    }
	return &result;
}

int *
modifier_client_1_svc(client *argp, struct svc_req *rqstp)
{
	static int  result;
	
	int i;
	for(i=0;i<10; i++){ 
        	if (listClient[i].id==argp->id){
     			
     			 if (argp->carteBancaire != 0)
     			{
     			listClient[i].carteBancaire=argp->carteBancaire;
     			result = 1;
     			printf("--modification du carte bancaire est bien effectuer--\n");
     			printf("-------------------------------------------------\n");
			}	
        	}
        }
	return &result;
}

recettes *
rechercher_recette_1_svc(type_chaine *argp, struct svc_req *rqstp)
{
	
	static recettes  result;
	result.nbRecette = 0;
	int i;
	for(i=0;i<nbRecette; i++){ 
        	if (strcmp(listRecette[i].type,argp->chaine)==0){
		    result.listeRecette[result.nbRecette]=listRecette[i];
		    result.nbRecette++;
		   
        }
    }
	 printf("--la recherch des recette de type VEGETARIEN--\n");
	 printf("-------------------------------------------------\n");

	return &result;
}

int *
ajout_au_panier_1_svc(panier *argp, struct svc_req *rqstp)
{
		static int  result;
	int i;
	double total=0.0;
	double prix=0.0;
	listPanier[indicePanier].id=argp->id;
	listPanier[indicePanier].idC=argp->idC;
	//initialiser id de recette
	for(i =0;i<10;i++){
		
		listPanier[indicePanier].id_recette[i]=argp->id_recette[i];
		
	}
	//Calculer Total
	for(i=0;i<10;i++){
		if(argp->id_recette[i] == listRecette[i].id){

			total = total + listRecette[i].prix;
		}	
	}
	listPanier[indicePanier].total=total;
	indicePanier++;
	result=indicePanier;
	printf("--ajouter au panier est bien--\n");
	printf("-------------------------------------------------\n");
	//printf("le total %f",total);
	return &result;
}
panier *
afficher_panier_1_svc(int *argp, struct svc_req *rqstp)
{
	static panier  result;
	int i,j;
	for(i=0;i<10; i++){ 
        	if (listPanier[i].id==*argp){
		    result.id=*argp;
		    result.idC=listPanier[i].idC;
			    for(j=0 ;j<10;j++){
			    
			    	result.id_recette[j]=listPanier[i].id_recette[j];
			    
			    }
		    result.total=listPanier[i].total;
        }
    }
    printf("--affichage du panier est bien effectuer--\n");
    printf("-------------------------------------------------\n");
    

	return &result;
}
int *
supprimer_recette_au_panier_1_svc(panier *argp, struct svc_req *rqstp)
{
	

static int  result;
	double total=0.0;
	int i,j,k;
	for(i=0;i<10; i++){ 
        	if (listPanier[i].id==argp->id){
     			for(j=0;j<10;j++){
	     			listPanier[i].id_recette[j]=argp->id_recette[j];

	     				
			}
			for(k=0;k<10;k++){
		     			if(argp->id_recette[k] == listRecette[k].id){
							if(argp->id_recette[k] != 0){
								total = total + listRecette[k].prix;
								
						}
					}
				}
			listPanier[i].total=total;
			printf("--la modification au panier est bien effectuer\n");
			printf("-------------------------------------------------\n");
        	}
        				
		
        }
   
        
        result=1;

	return &result;
}

int *
effectuer_commande_1_svc(commande *argp, struct svc_req *rqstp)
{
	static int  result;

	listCommande[nbCommande].id=nbCommande+1;
	listCommande[nbCommande].idPanier=argp->idPanier;
	listCommande[nbCommande].date.day=argp->date.day;
	listCommande[nbCommande].date.mounth=argp->date.mounth;
	listCommande[nbCommande].date.year=argp->date.year;
	strcpy(listCommande[nbCommande].etat,argp->etat);
	result = 1;

nbCommande++;
printf("--la commande est confirmer\n");
printf("-------------------------------------------------\n");
	return &result;
}

commande *
afficher_commande_1_svc(int *argp, struct svc_req *rqstp)
{
	static commande  result;

	int i;
	for(i=0;i<10; i++){ 
        	if (listCommande[i].id==*argp){
		    
		    result.idPanier=listCommande[i].idPanier;
		        result.date.day=listCommande[i].date.day;
		         result.date.mounth=listCommande[i].date.mounth;
		         result.date.year=listCommande[i].date.year;
		    strcpy(result.etat,listCommande[i].etat);
		
		    printf("--l'affichage du details du commande \n");
		    printf("-------------------------------------------------\n");
        }
    }
	return &result;
}

int *
programmer_livraison_1_svc(livraison *argp, struct svc_req *rqstp)
{
	static int  result;
	strcpy(listLivraison[nbLivraison].adresse,argp->adresse);
	listLivraison[nbLivraison].idCommande=argp->idCommande;
	listLivraison[nbLivraison].date.day=argp->date.day;
	listLivraison[nbLivraison].date.mounth=argp->date.mounth;
	listLivraison[nbLivraison].date.year=argp->date.year;
	strcpy(listLivraison[nbLivraison].type,argp->type);
	nbLivraison++;
	printf("--la livraison est programmer \n");
	printf("--la commande va etre LIVRER \n");
	
	return &result;
}
