/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "quitoque.h"

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tele))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->adresse, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->carteBancaire))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->day))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mounth))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->year))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_commande (XDR *xdrs, commande *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idPanier))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->qte))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->etat, 1,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_livraison (XDR *xdrs, livraison *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idCommande))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->adresse, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->type, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_recette (XDR *xdrs, recette *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->type, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ingrediant, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbPart))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->disponible, 1,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_panier (XDR *xdrs, panier *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (2 + ( 10 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->idC))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->id_recette, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->id);
		IXDR_PUT_LONG(buf, objp->idC);
		{
			register int *genp;

			for (i = 0, genp = objp->id_recette;
				i < 10; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_double (xdrs, &objp->total))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (2 + ( 10 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->idC))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->id_recette, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		objp->id = IXDR_GET_LONG(buf);
		objp->idC = IXDR_GET_LONG(buf);
		{
			register int *genp;

			for (i = 0, genp = objp->id_recette;
				i < 10; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		}
		 if (!xdr_double (xdrs, &objp->total))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idC))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->id_recette, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->total))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_recettes (XDR *xdrs, recettes *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->listeRecette, 10,
		sizeof (recette), (xdrproc_t) xdr_recette))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbRecette))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_type_chaine (XDR *xdrs, type_chaine *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->chaine, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
