/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUITOQUE_H_RPCGEN
#define _QUITOQUE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct client {
	int id;
	char nom[10];
	char prenom[10];
	int tele;
	char adresse[20];
	long carteBancaire;
};
typedef struct client client;

struct date {
	int day;
	int mounth;
	int year;
};
typedef struct date date;

struct commande {
	int id;
	int idPanier;
	date date;
	int qte;
	char etat[1];
};
typedef struct commande commande;

struct livraison {
	int id;
	int idCommande;
	date date;
	char adresse[20];
	char type[10];
};
typedef struct livraison livraison;

struct recette {
	int id;
	char nom[10];
	char type[10];
	char ingrediant[20];
	int nbPart;
	double prix;
	char disponible[1];
};
typedef struct recette recette;

struct panier {
	int id;
	int idC;
	int id_recette[10];
	double total;
};
typedef struct panier panier;

struct recettes {
	recette listeRecette[10];
	int nbRecette;
};
typedef struct recettes recettes;

struct type_chaine {
	char chaine[10];
};
typedef struct type_chaine type_chaine;

#define QUITOQUE_PROG 0x23456789
#define QUITOQUE_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  void * init_1(void *, CLIENT *);
extern  void * init_1_svc(void *, struct svc_req *);
#define ajout_client 2
extern  int * ajout_client_1(client *, CLIENT *);
extern  int * ajout_client_1_svc(client *, struct svc_req *);
#define afficher_client 3
extern  client * afficher_client_1(int *, CLIENT *);
extern  client * afficher_client_1_svc(int *, struct svc_req *);
#define modifier_client 4
extern  int * modifier_client_1(client *, CLIENT *);
extern  int * modifier_client_1_svc(client *, struct svc_req *);
#define rechercher_recette 5
extern  recettes * rechercher_recette_1(type_chaine *, CLIENT *);
extern  recettes * rechercher_recette_1_svc(type_chaine *, struct svc_req *);
#define ajout_au_panier 6
extern  int * ajout_au_panier_1(panier *, CLIENT *);
extern  int * ajout_au_panier_1_svc(panier *, struct svc_req *);
#define afficher_panier 7
extern  panier * afficher_panier_1(int *, CLIENT *);
extern  panier * afficher_panier_1_svc(int *, struct svc_req *);
#define supprimer_recette_au_panier 8
extern  int * supprimer_recette_au_panier_1(panier *, CLIENT *);
extern  int * supprimer_recette_au_panier_1_svc(panier *, struct svc_req *);
#define effectuer_commande 9
extern  int * effectuer_commande_1(commande *, CLIENT *);
extern  int * effectuer_commande_1_svc(commande *, struct svc_req *);
#define afficher_commande 10
extern  commande * afficher_commande_1(int *, CLIENT *);
extern  commande * afficher_commande_1_svc(int *, struct svc_req *);
#define programmer_livraison 11
extern  int * programmer_livraison_1(livraison *, CLIENT *);
extern  int * programmer_livraison_1_svc(livraison *, struct svc_req *);
extern int quitoque_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  void * init_1();
extern  void * init_1_svc();
#define ajout_client 2
extern  int * ajout_client_1();
extern  int * ajout_client_1_svc();
#define afficher_client 3
extern  client * afficher_client_1();
extern  client * afficher_client_1_svc();
#define modifier_client 4
extern  int * modifier_client_1();
extern  int * modifier_client_1_svc();
#define rechercher_recette 5
extern  recettes * rechercher_recette_1();
extern  recettes * rechercher_recette_1_svc();
#define ajout_au_panier 6
extern  int * ajout_au_panier_1();
extern  int * ajout_au_panier_1_svc();
#define afficher_panier 7
extern  panier * afficher_panier_1();
extern  panier * afficher_panier_1_svc();
#define supprimer_recette_au_panier 8
extern  int * supprimer_recette_au_panier_1();
extern  int * supprimer_recette_au_panier_1_svc();
#define effectuer_commande 9
extern  int * effectuer_commande_1();
extern  int * effectuer_commande_1_svc();
#define afficher_commande 10
extern  commande * afficher_commande_1();
extern  commande * afficher_commande_1_svc();
#define programmer_livraison 11
extern  int * programmer_livraison_1();
extern  int * programmer_livraison_1_svc();
extern int quitoque_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client (XDR *, client*);
extern  bool_t xdr_date (XDR *, date*);
extern  bool_t xdr_commande (XDR *, commande*);
extern  bool_t xdr_livraison (XDR *, livraison*);
extern  bool_t xdr_recette (XDR *, recette*);
extern  bool_t xdr_panier (XDR *, panier*);
extern  bool_t xdr_recettes (XDR *, recettes*);
extern  bool_t xdr_type_chaine (XDR *, type_chaine*);

#else /* K&R C */
extern bool_t xdr_client ();
extern bool_t xdr_date ();
extern bool_t xdr_commande ();
extern bool_t xdr_livraison ();
extern bool_t xdr_recette ();
extern bool_t xdr_panier ();
extern bool_t xdr_recettes ();
extern bool_t xdr_type_chaine ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUITOQUE_H_RPCGEN */
